# Generated by Django 4.2.7 on 2023-11-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desempregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=10)),
                ('cpnj', models.DecimalField(decimal_places=2, max_digits=14)),
                ('endereco', models.CharField(max_length=50)),
                ('segmento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_procuraEmprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=40)),
                ('desempregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desempregado')),
            ],
        ),
    ]
