# Generated by Django 4.2.7 on 2023-11-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario_procuraemprego',
            name='desempregado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cpnj',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='segmento',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Desempregado',
        ),
        migrations.DeleteModel(
            name='Usuario_procuraEmprego',
        ),
        migrations.AddField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
    ]
