# Generated by Django 4.2.7 on 2023-11-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidato_login_usuario_vaga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
