# Generated by Django 4.2.7 on 2023-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuario_login_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='vaga',
        ),
    ]
