# Generated by Django 4.2.7 on 2023-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_candidato_vaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cpnj',
            new_name='cnpj',
        ),
    ]
