# Generated by Django 4.2.7 on 2023-11-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidato_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='salario',
        ),
    ]
