# Generated by Django 4.2.7 on 2023-11-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_candidato_user_empresa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='user',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
    ]
