# Generated by Django 4.2.7 on 2023-11-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_candidato_user_remove_empresa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome',
            new_name='razao_social',
        ),
    ]
